version: 2

jobs:
  one:
    docker:
      - image: meteor/circleci:android-28-node-12
    steps:
      - checkout
      - run: |
          curl https://install.meteor.com/ | sh
          cd test-app
          ./ci.sh

workflows:
  version: 2
  onejob:
    jobs:
      - one
