version: 2

jobs:
  one:
    docker:
      - image: meteor/circleci:android-28-node-12
    steps:
      - checkout
      - run:
        name: "Install Meteor"
        command: curl https://install.meteor.com/ | sh
      - run:
        name: "Run Tests"
        command: |
          cd test-app
          pwd
          ./ci.sh

workflows:
  version: 2
  onejob:
    jobs:
      - one
